### ISSUE TITLE
can't import openmm, openmm app ...

### ISSUE THREAD

**Issue by mateoalpha98** [openmm/openmm-org#91]
The code i've been using for the last three months worked well until Monday, but now it appears this message:
python3 code.py 
Traceback (most recent call last):
  File "/home/mateoc/Documentos/practiques/tleap_propka/code.py", line 1, in <module>
    from simtk.openmm.app import *
  File "/home/mateoc/miniconda3/envs/openmm/lib/python3.10/site-packages/simtk/__init__.py", line 1, in <module>
    import openmm
  File "/home/mateoc/Documentos/practiques/tleap_propka/openmm.py", line 1, in <module>
    from openmm.app import *
ModuleNotFoundError: No module named 'openmm.app'; 'openmm' is not a package

the way I used to import this libraries is this one:
from openmm.app import *
from openmm import *
from simtk.unit import * 
from openmm import app

**Comment by peastman** [comment]
Could you move this to https://github.com/openmm/openmm?  This repository is for the website, not for users of OpenMM.
